name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:    
  build:
    name: Buildear Django
    runs-on: ubuntu-latest
    
    steps:
    - name: install SSH keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: connect, checkout and deploy
      run:  ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} 
          && git checkout ${{ secrets.MAIN_BRANCH }} 
          && git pull 
          && bash entrypoint.sh
          && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
